package com.erp.view.panels.marketing;

import com.erp.util.Constants;
import com.erp.view.panels.BasePanel;

import javax.swing.*;
import java.awt.*;

/**
 * MarketingPanel - Main container for Marketing module with tabbed navigation.
 *
 * Contains:
 * - Campaigns Tab: Manage marketing campaigns with full CRUD
 * - Lead Tracking Tab: Track leads generated by campaigns
 * - Analytics Tab: Marketing spend, ROI, and performance metrics
 */
public class MarketingPanel extends BasePanel {

    private JTabbedPane tabbedPane;
    private CampaignsPanel campaignsPanel;
    private LeadTrackingPanel leadTrackingPanel;
    private MarketingAnalyticsPanel analyticsPanel;

    public MarketingPanel() {
        super(Constants.MODULE_MARKETING);
    }

    @Override
    protected void initializeComponents() {
        // Create tab panels
        campaignsPanel = new CampaignsPanel();
        leadTrackingPanel = new LeadTrackingPanel();
        analyticsPanel = new MarketingAnalyticsPanel();

        // Create tabbed pane
        tabbedPane = new JTabbedPane(JTabbedPane.TOP);
        tabbedPane.setFont(Constants.FONT_REGULAR);
        tabbedPane.setBackground(Constants.BG_WHITE);

        // Add tabs
        tabbedPane.addTab("Campaigns", campaignsPanel);
        tabbedPane.addTab("Lead Tracking", leadTrackingPanel);
        tabbedPane.addTab("Analytics", analyticsPanel);

        // Refresh data when tab changes
        tabbedPane.addChangeListener(e -> {
            int index = tabbedPane.getSelectedIndex();
            switch (index) {
                case 0: campaignsPanel.refreshData(); break;
                case 1: leadTrackingPanel.refreshData(); break;
                case 2: analyticsPanel.refreshData(); break;
            }
        });
    }

    @Override
    protected void layoutComponents() {
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(tabbedPane, BorderLayout.CENTER);
    }

    @Override
    public void refreshData() {
        int index = tabbedPane.getSelectedIndex();
        switch (index) {
            case 0: campaignsPanel.refreshData(); break;
            case 1: leadTrackingPanel.refreshData(); break;
            case 2: analyticsPanel.refreshData(); break;
        }
    }
}
