package com.erp.service.interfaces;

import com.erp.model.Campaign;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

/**
 * MarketingService Interface - CONTRACT for Marketing Module Backend Team
 *
 * Covers: Campaign Management, Customer Segmentation, Lead Generation, Marketing Analytics
 */
public interface MarketingService {

    // ==================== CAMPAIGN MANAGEMENT ====================

    /**
     * Get all campaigns.
     * @return List of all campaigns
     */
    List<Campaign> getAllCampaigns();

    /**
     * Get campaigns by status.
     * @param status PLANNED, ACTIVE, PAUSED, COMPLETED, CANCELLED
     * @return List of campaigns
     */
    List<Campaign> getCampaignsByStatus(String status);

    /**
     * Get campaigns by type.
     * @param type EMAIL, SOCIAL_MEDIA, ADS, EVENT, CONTENT, etc.
     * @return List of campaigns
     */
    List<Campaign> getCampaignsByType(String type);

    /**
     * Get active campaigns.
     * @return List of currently active campaigns
     */
    List<Campaign> getActiveCampaigns();

    /**
     * Get a campaign by ID.
     * @param campaignId The campaign ID
     * @return Campaign or null
     */
    Campaign getCampaignById(int campaignId);

    /**
     * Create a new campaign.
     * @param campaign The campaign data
     * @return Created campaign with ID
     */
    Campaign createCampaign(Campaign campaign);

    /**
     * Update a campaign.
     * @param campaign The campaign to update
     * @return true if successful
     */
    boolean updateCampaign(Campaign campaign);

    /**
     * Start a campaign.
     * @param campaignId The campaign ID
     * @return true if started
     */
    boolean startCampaign(int campaignId);

    /**
     * Pause a campaign.
     * @param campaignId The campaign ID
     * @return true if paused
     */
    boolean pauseCampaign(int campaignId);

    /**
     * End a campaign.
     * @param campaignId The campaign ID
     * @return true if ended
     */
    boolean endCampaign(int campaignId);

    /**
     * Delete a campaign.
     * @param campaignId The campaign ID
     * @return true if deleted
     */
    boolean deleteCampaign(int campaignId);


    // ==================== LEAD MANAGEMENT ====================

    /**
     * Record a lead generated by a campaign.
     * @param campaignId The campaign ID
     * @param customerId The customer/lead ID
     * @return true if recorded
     */
    boolean recordLead(int campaignId, int customerId);

    /**
     * Get leads generated by a campaign.
     * @param campaignId The campaign ID
     * @return List of customer IDs
     */
    List<Integer> getLeadsByCampaign(int campaignId);

    /**
     * Get lead count by campaign.
     * @param campaignId The campaign ID
     * @return Number of leads
     */
    int getLeadCount(int campaignId);


    // ==================== MARKETING ANALYTICS ====================

    /**
     * Get campaign performance metrics.
     * @param campaignId The campaign ID
     * @return Map with keys: leads, conversions, cost, roi, etc.
     */
    Map<String, Object> getCampaignMetrics(int campaignId);

    /**
     * Get total marketing spend for a period.
     * @param startDate Start date
     * @param endDate End date
     * @return Total spend
     */
    BigDecimal getTotalMarketingSpend(LocalDate startDate, LocalDate endDate);

    /**
     * Get marketing spend by campaign type.
     * @param startDate Start date
     * @param endDate End date
     * @return Map of type to spend
     */
    Map<String, BigDecimal> getSpendByType(LocalDate startDate, LocalDate endDate);

    /**
     * Get conversion rate (leads to customers).
     * @param campaignId The campaign ID (0 for overall)
     * @return Conversion percentage
     */
    double getConversionRate(int campaignId);

    /**
     * Get cost per lead.
     * @param campaignId The campaign ID
     * @return Cost per lead
     */
    BigDecimal getCostPerLead(int campaignId);

    /**
     * Get campaign ROI.
     * @param campaignId The campaign ID
     * @return ROI percentage
     */
    double getCampaignROI(int campaignId);
}
